services:
  tasks.api:
    image: ${DOCKER_REGISTRY-}tasksapi
    build:
      context: .
      dockerfile: ./src/Tasks.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=data/tasks.db
      - JwtSettings__Secret=SuperSecretTestingKeyEnsureItIsLongEnough32Bytes!
      - JwtSettings__Issuer=TasksApi
      - JwtSettings__Audience=TasksUi
    volumes:
      - ./data:/app/data